image: "thlmylab/swakkd:1.23"

stages:
  - prepare
  - build
  - deploy
  - expose
  - terminate

secrets:
  stage: prepare
  script:
    - kubectl delete secret gitlab-registry-$CI_PROJECT_ID || true
    - "kubectl create secret docker-registry gitlab-registry-$CI_PROJECT_ID \
            --docker-server=$CI_REGISTRY \
            --docker-username=image-registry \ 
            --docker-password=$CI_REGISTRY_TOKEN \ 
      "

create-pvc:
  stage: prepare
  script:
    - kubectl apply -f deploy/space-run-pvc.yaml

container:
  image: docker:dind
  services: [ "docker:dind" ]
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/rest-api:latest .
    - docker push $CI_REGISTRY_IMAGE/rest-api:latest


deploy:
  stage: deploy
  script:
    - mo deploy/space-run-dep.yaml | kubectl delete -f - || true
    - mo deploy/space-run-dep.yaml | kubectl apply -f -
    - mo deploy/space-run-svc.yaml | kubectl apply -f -

ingress:
  stage: expose
  when: manual
  script:
    - mo deploy/space-run-ing.yaml | kubectl apply -f -

shut-down:
  stage: terminate
  when: manual
  script:
    - mo deploy/space-run-dep.yaml | kubectl delete -f - || true
    - mo deploy/space-run-svc.yaml | kubectl delete -f - || true
    - mo deploy/space-run-ing.yaml | kubectl delete -f - || true
    - kubectl delete -f deploy/space-run-pvc.yaml || true