apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: space-run-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt"
    acme.cert-manager.io/http01-edit-in-place: "true"
spec:
  rules:
    - host: space-run-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: space-run-service
                port:
                  number: 80
  tls:
    - secretName: space-run-ingress-cert
      hosts:
        - space-run-{{ CI_PROJECT_ID }}.edu.k8s.th-luebeck.dev
